-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdz60jFGcTVMdXRu0
ujrGH7wglv6Q7LNbepONduUo1BugCgYIKoZIzj0DAQehRANCAATVyRd5FWO7QFhm
Mm9GjUS6FYJAX4y/JDbjgxigImgQld/HpSgJOi2xi/0iT1Yk//ym+WXktxxK2PGF
t4kwg20s
-----END PRIVATE KEY-----