workflows:
  ios_testflight:
    name: iOS TestFlight Build
    instance_type: mac_mini_m1
    max_build_duration: 45
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.aqvioo.akvioo"
        XCODE_PROJECT: "ios/Runner.xcodeproj"
        XCODE_SCHEME: "Runner"
      ios_signing:
        provisioning_profiles:
          - profile_name: "Aqvioo App Store profile"
            bundle_id: "com.aqvioo.akvioo"
        certificates:
          - certificate_name: "iOS Development"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS App
        script: |
          flutter build ipa --release \
            -t lib/main.dart
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        submit_to_testflight: true
        beta_groups:
          - Internal

  ios_app_store:
    name: iOS App Store Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.aqvioo.akvioo"
        XCODE_PROJECT: "ios/Runner.xcodeproj"
        XCODE_SCHEME: "Runner"
      ios_signing:
        provisioning_profiles:
          - profile_name: "Aqvioo App Store"
            bundle_id: "com.aqvioo.akvioo"
        certificates:
          - certificate_name: "Distribution"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS App
        script: |
          flutter build ipa --release \
            -t lib/main.dart
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        submit_to_app_store: true
        release_type: MANUAL