workflows:
  ios-testflight:
    name: iOS Build for TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Aqvioo API Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aqvioo.akvioo
      vars:
        KIE_API_KEY: $KIE_API_KEY
        OPENAI_API_KEY: $OPENAI_API_KEY
        ELEVEN_LABS_API_KEY: $ELEVEN_LABS_API_KEY
        TAP_SECRET_KEY: $TAP_SECRET_KEY
        TAP_PUBLIC_KEY: $TAP_PUBLIC_KEY
        TAP_MERCHANT_ID: $TAP_MERCHANT_ID
        TAP_TEST_MODE: $TAP_TEST_MODE
        APP_STORE_APPLE_ID: "6756293641"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create .env file
        script: |
          echo "KIE_API_KEY=$KIE_API_KEY" >> .env
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
          echo "ELEVEN_LABS_API_KEY=$ELEVEN_LABS_API_KEY" >> .env
          echo "TAP_SECRET_KEY=$TAP_SECRET_KEY" >> .env
          echo "TAP_PUBLIC_KEY=$TAP_PUBLIC_KEY" >> .env
          echo "TAP_MERCHANT_ID=$TAP_MERCHANT_ID" >> .env
          echo "TAP_TEST_MODE=$TAP_TEST_MODE" >> .env
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: cd ios && pod install
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=$CM_BUILD_DIR/ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - "Aseef2023@hotmail.com"
          - "mbardouni44@gmail.com"
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
        release_type: MANUAL
        beta_groups:
          - Internal Testers

  ios-development:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        KIE_API_KEY: $KIE_API_KEY
        OPENAI_API_KEY: $OPENAI_API_KEY
        ELEVEN_LABS_API_KEY: $ELEVEN_LABS_API_KEY
        TAP_SECRET_KEY: $TAP_SECRET_KEY
        TAP_PUBLIC_KEY: $TAP_PUBLIC_KEY
        TAP_MERCHANT_ID: $TAP_MERCHANT_ID
        TAP_TEST_MODE: $TAP_TEST_MODE
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
        - pattern: feature/*
          include: true
    scripts:
      - name: Create .env file
        script: |
          echo "KIE_API_KEY=$KIE_API_KEY" >> .env
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
          echo "ELEVEN_LABS_API_KEY=$ELEVEN_LABS_API_KEY" >> .env
          echo "TAP_SECRET_KEY=$TAP_SECRET_KEY" >> .env
          echo "TAP_PUBLIC_KEY=$TAP_PUBLIC_KEY" >> .env
          echo "TAP_MERCHANT_ID=$TAP_MERCHANT_ID" >> .env
          echo "TAP_TEST_MODE=$TAP_TEST_MODE" >> .env
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: cd ios && pod install
      - name: Flutter analyze
        script: flutter analyze --no-fatal-infos
      - name: Flutter build iOS (no codesign)
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - "Aseef2023@hotmail.com"
        notify:
          success: false
          failure: true

  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        KIE_API_KEY: $KIE_API_KEY
        OPENAI_API_KEY: $OPENAI_API_KEY
        ELEVEN_LABS_API_KEY: $ELEVEN_LABS_API_KEY
        TAP_SECRET_KEY: $TAP_SECRET_KEY
        TAP_PUBLIC_KEY: $TAP_PUBLIC_KEY
        TAP_MERCHANT_ID: $TAP_MERCHANT_ID
        TAP_TEST_MODE: $TAP_TEST_MODE
      flutter: stable
      java: 17
    scripts:
      - name: Create .env file
        script: |
          echo "KIE_API_KEY=$KIE_API_KEY" >> .env
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
          echo "ELEVEN_LABS_API_KEY=$ELEVEN_LABS_API_KEY" >> .env
          echo "TAP_SECRET_KEY=$TAP_SECRET_KEY" >> .env
          echo "TAP_PUBLIC_KEY=$TAP_PUBLIC_KEY" >> .env
          echo "TAP_MERCHANT_ID=$TAP_MERCHANT_ID" >> .env
          echo "TAP_TEST_MODE=$TAP_TEST_MODE" >> .env
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze --no-fatal-infos
      - name: Flutter build APK
        script: flutter build apk --release
      - name: Flutter build App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - "Aseef2023@hotmail.com"
        notify:
          success: true
          failure: true
