workflows:
  default:
    name: Default Workflow - iOS App Store Only
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
        - pattern: 'credit'
        - pattern: 'develop'
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aqvioo.akvioo
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create .env file
        script: |
          echo "KIE_API_KEY=$KIE_API_KEY" >> .env
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
          echo "ELEVEN_LABS_API_KEY=$ELEVEN_LABS_API_KEY" >> .env
          echo "TAP_SECRET_KEY=$TAP_SECRET_KEY" >> .env
          echo "TAP_PUBLIC_KEY=$TAP_PUBLIC_KEY" >> .env
          echo "TAP_MERCHANT_ID=$TAP_MERCHANT_ID" >> .env
          echo "TAP_TEST_MODE=$TAP_TEST_MODE" >> .env
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.aqvioo.akvioo" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Get dependencies
        script: flutter pub get
      - name: Clean pods cache
        script: |
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
      - name: Install pods
        script: |
          export COCOAPODS_DISABLE_STATS=true
          cd ios && pod install --repo-update && cd ..
      - name: Patch gRPC-Core for Xcode 16.3
        script: |
          # Fix gRPC-Core C++ template issue (Xcode 16.3 compatibility)
          GRPC_FILE="ios/Pods/gRPC-Core/src/core/lib/promise/detail/basic_seq.h"
          if [ -f "$GRPC_FILE" ]; then
            echo "Patching gRPC-Core basic_seq.h..."
            sed -i '' 's/Traits::template CallSeqFactory(/Traits::template CallSeqFactory<>(/g' "$GRPC_FILE"
            echo "Patch applied successfully"
          else
            echo "Warning: gRPC-Core file not found at $GRPC_FILE"
            find ios/Pods -name "basic_seq.h" 2>/dev/null || echo "No basic_seq.h found"
          fi
      - name: Build IPA
        script: |
          xcode-project use-profiles
          flutter build ipa --release --build-number=$BUILD_NUMBER --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
      email:
        recipients:
          - Aseef2023@hotmail.com