// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmxSaHG6CDRO5a7_MRH4U8SpcUNpBgVpo',
    appId: '1:651649539964:web:3ebd906b5765c3d226cef9',
    messagingSenderId: '651649539964',
    projectId: 'beldify-b445b',
    authDomain: 'beldify-b445b.firebaseapp.com',
    storageBucket: 'beldify-b445b.firebasestorage.app',
    measurementId: 'G-9TWF1NFCW3',
  );

  // TODO: Configure Android app in Firebase Console and replace placeholder App ID
  // Phone auth requires: 1) Real App ID, 2) SHA-1 certificate added to Firebase Console
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmxSaHG6CDRO5a7_MRH4U8SpcUNpBgVpo',
    appId:
        '1:651649539964:android:YOUR_ANDROID_APP_ID', // <-- Replace with real App ID from Firebase Console
    messagingSenderId: '651649539964',
    projectId: 'beldify-b445b',
    authDomain: 'beldify-b445b.firebaseapp.com',
    storageBucket: 'beldify-b445b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPm59HesfNtYYt88NjDW46XOjFvWMwHU4',
    appId: '1:651649539964:ios:60a0c21c67ff49f626cef9',
    messagingSenderId: '651649539964',
    projectId: 'beldify-b445b',
    storageBucket: 'beldify-b445b.firebasestorage.app',
    iosBundleId: 'com.aqvioo.akvioo',
  );
}
